{{- if .Values.externalSecret.enabled -}}
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "job-database.fullname" . }}
  labels:
    {{- include "job-database.labels" . | nindent 4 }}
  {{- with .Values.externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h0m0s" }}
  {{- with .Values.externalSecret.secretStoreRef }}
  secretStoreRef:
    kind: {{ .kind | default "ClusterSecretStore" }}
    name: {{ .name | default "" }}
  {{- end }}
  target:
    name: {{ .Values.externalSecret.target.name | default (include "job-database.fullname" .) }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy | default "Owner" }}
  data:
  {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRefKey }}
  {{- end }}
{{- end }}