{{- if .Values.secret.enabled -}}
---
apiVersion: external-secrets.io/v1alpha1
kind: Secret
metadata:
  name: {{ include "job-database.fullname" . }}
  labels:
    {{- include "job-database.labels" . | nindent 4 }}
  {{- with .Values.externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
